### ISSUE TITLE
GSL: 'Guideline support library' inclusion

### ISSUE THREAD

**Issue by kknox** [kknox/CppCoreGuidelines#2]
I propose our libraries use the GSL: 'Guideline support library'  advocated by the CppCoreGuidelines.
 
* many of their rules assume it's existence.  
* It is a header only file, so no binary dependencies
* Code correctness tools will be written to understand the types is provides
* The installation of the header files can be automated with cmake

**Comment by kknox** [comment]
According to the published 'Supported Platforms' section (for microsoft's implementation), this may dictate that we document a minimum of clang 3.6 dependency.

**Comment by tingxingdong** [comment]
**I can not install.**

**by "cmake --help" I get**
_Generators

_The following generators are available on this platform:
  Unix Makefiles              = Generates standard UNIX makefiles.
  Ninja                       = Generates build.ninja files (experimental).
  CodeBlocks - Ninja          = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles = Generates CodeBlocks project files.
  Eclipse CDT4 - Ninja        = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles
                              = Generates Eclipse CDT 4.0 project files.
  KDevelop3                   = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles  = Generates KDevelop 3 project files.
  Sublime Text 2 - Ninja      = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                              = Generates Sublime Text 2 project files.__

Then, I choose Unix Makefiles
**"cmake -G "Unix Makefiles" ~/GSL/" give me tons of C++ error**
__
/home/tim/GSL/tests/../include/string_span.h:921:22: error: expected ‘>’
In file included from /home/tim/GSL/tests/assertion_tests.cpp:18:0:
/home/tim/GSL/tests/../include/gsl.h:87:44: error: expected type-specifier
     template <typename U, typename Dummy = std::enable_if_t<std::is_convertible<U, T>::value>>_

**Comment by kknox** [comment]
They document their [supported compilers](https://github.com/Microsoft/GSL#supported-platforms).  You may need to manually install and specify clang on your machine, or install GCC 5.1 yourself.  I assume that you are trying to use gcc 4.8 from Ubuntu 14.04?

**Comment by tingxingdong** [comment]
gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by tingxingdong** [comment]
by "apt-get update & install gcc-5", I get gcc-5.3 instead of v5.1. 
I put gcc(g++)5.3  as the default gcc compiler (before it is v4.8). 

Then run "cmake -G "KDevelop3" ~/GSL"  and follow the steps. It works on my ubuntu 14.04
" 
100% tests passed, 0 tests failed out of 9
"
